-- Reference data: quiz style anchors and launch brands (fashion, US).
insert into public.style_anchors (slug, label, anchor_text, sort_order, image_url) values
('minimalist', 'Minimalist', 'fashion post. Style: minimalist, clean basics, capsule wardrobe. Neutral palette, tailored trousers, white tee, quality knits, understated silhouettes. Brands: COS, Everlane, Uniqlo.', 1, 'https://picsum.photos/seed/style-minimalist/600/800'),
('old_money', 'Old Money', 'fashion post. Style: old money, quiet luxury, classic. Cashmere, camel coat, loafers, trench, pearls, tailored blazer, polished timeless dressing. Brands: The Row, Ralph Lauren, Toteme.', 2, 'https://picsum.photos/seed/style-oldmoney/600/800'),
('streetwear', 'Streetwear', 'fashion post. Style: streetwear, hype, sneakers. Oversized hoodie, graphic tee, cargo pants, baggy denim, Jordans, caps, layered fits. Brands: Nike, Stüssy, Carhartt WIP.', 3, 'https://picsum.photos/seed/style-street/600/800'),
('athleisure', 'Athleisure', 'fashion post. Style: athleisure, activewear, gym to street. Leggings, matching sets, sports bra, zip-up, sneakers, comfortable performance fabrics. Brands: Lululemon, Alo Yoga, Nike.', 4, 'https://picsum.photos/seed/style-athleisure/600/800'),
('workwear', 'Workwear', 'fashion post. Style: workwear, office, smart. Tailored trousers, blazer, button-down, pencil skirt, pointed flats, polished 9-to-5 outfits. Brands: J.Crew, Aritzia, Theory.', 5, 'https://picsum.photos/seed/style-work/600/800'),
('scandi', 'Scandi', 'fashion post. Style: scandi, Scandinavian, effortless. Oversized blazer, straight-leg jeans, chunky knit, muted tones, relaxed proportions, clean layering. Brands: Ganni, COS, Toteme.', 6, 'https://picsum.photos/seed/style-scandi/600/800'),
('model_off_duty', 'Model Off Duty', 'fashion post. Style: model off duty, clean girl, effortless cool. Straight jeans, white tank, leather jacket, slicked-back hair, sneakers or boots, minimal jewelry. Brands: Aritzia, Zara, Levi''s.', 7, 'https://picsum.photos/seed/style-mod/600/800'),
('gorpcore', 'Gorpcore', 'fashion post. Style: gorpcore, outdoor, technical. Puffer, fleece, hiking boots, shell jacket, cargo, trail runners, functional layered outdoor wear. Brands: Arc''teryx, Patagonia, Salomon.', 8, 'https://picsum.photos/seed/style-gorp/600/800'),
('coastal', 'Coastal', 'fashion post. Style: coastal, beachy, breezy. Linen sets, white dress, sandals, raffia bag, striped knits, relaxed summer vacation dressing. Brands: Reformation, Madewell, Zara.', 9, 'https://picsum.photos/seed/style-coastal/600/800'),
('cottagecore', 'Cottagecore', 'fashion post. Style: cottagecore, romantic, prairie. Floral midi dress, puff sleeves, linen, smocking, straw hat, soft pastoral vintage feel. Brands: Free People, Reformation, Anthropologie.', 10, 'https://picsum.photos/seed/style-cottage/600/800'),
('y2k', 'Y2K', 'fashion post. Style: Y2K, 2000s revival, playful. Low-rise jeans, baby tee, mini skirt, butterfly clips, metallics, rhinestones, going-out cami. Brands: Princess Polly, Urban Outfitters, Miu Miu.', 11, 'https://picsum.photos/seed/style-y2k/600/800'),
('preppy', 'Preppy', 'fashion post. Style: preppy, collegiate, classic American. Polo, cable knit sweater, pleated skirt, chinos, loafers, stripes, tennis and country club looks. Brands: Ralph Lauren, J.Crew, Abercrombie & Fitch.', 12, 'https://picsum.photos/seed/style-preppy/600/800'),
('glam', 'Glam', 'fashion post. Style: glam, going out, night out. Mini dress, satin, sequins, corset top, heels, statement bag, party and date-night outfits. Brands: Princess Polly, Zara, Saint Laurent.', 13, 'https://picsum.photos/seed/style-glam/600/800'),
('vintage', 'Vintage', 'fashion post. Style: vintage, thrifted, retro. Secondhand denim, 70s and 90s pieces, leather jacket, unique one-of-a-kind finds, mixed eras. Brands: Levi''s, Coach, Gap.', 14, 'https://picsum.photos/seed/style-vintage/600/800'),
('boho', 'Boho', 'fashion post. Style: boho, bohemian, free-spirited. Flowy maxi dress, crochet, fringe, suede, layered jewelry, earthy prints, festival looks. Brands: Free People, Anthropologie, Urban Outfitters.', 15, 'https://picsum.photos/seed/style-boho/600/800'),
('grunge', 'Grunge', 'fashion post. Style: grunge, alternative, edgy. Black denim, band tee, combat boots, plaid flannel, leather jacket, ripped tights, dark layered looks. Brands: Urban Outfitters, Dr. Martens, Levi''s.', 16, 'https://picsum.photos/seed/style-grunge/600/800'),
('coquette', 'Coquette', 'fashion post. Style: coquette, balletcore, girly. Bows, lace, ballet flats, wrap cardigan, soft pink, ribbon details, delicate feminine pieces. Brands: Miu Miu, Sandy Liang, Free People.', 17, 'https://picsum.photos/seed/style-coquette/600/800'),
('western', 'Western', 'fashion post. Style: western, cowgirl, americana. Cowboy boots, denim on denim, fringe jacket, suede, belt buckle, prairie skirt, rodeo-inspired outfits. Brands: Levi''s, Free People, Ralph Lauren.', 18, 'https://picsum.photos/seed/style-western/600/800');

insert into public.brands (name, price_band, style_tags, anchor_text, sort_order) values
('H&M', 'budget', '{minimalist}', 'fashion post. Style: minimalist, trend-led basics. Brands: H&M. Price: budget.', 1),
('Zara', 'budget', '{workwear,glam}', 'fashion post. Style: trend-led, workwear, going out. Brands: Zara. Price: budget.', 2),
('Uniqlo', 'budget', '{minimalist,scandi}', 'fashion post. Style: minimalist, basics, functional. Brands: Uniqlo. Price: budget.', 3),
('Old Navy', 'budget', '{}', 'fashion post. Style: casual everyday basics. Brands: Old Navy. Price: budget.', 4),
('Gap', 'budget', '{preppy,vintage}', 'fashion post. Style: casual, preppy, classic American denim. Brands: Gap. Price: budget.', 5),
('American Eagle', 'budget', '{y2k}', 'fashion post. Style: casual denim, Y2K, campus. Brands: American Eagle. Price: budget.', 6),
('Princess Polly', 'budget', '{y2k,glam,coquette}', 'fashion post. Style: Y2K, going out, girly. Brands: Princess Polly. Price: budget.', 7),
('Aritzia', 'mid', '{model_off_duty,workwear,minimalist}', 'fashion post. Style: elevated basics, model off duty, office. Brands: Aritzia. Price: mid.', 8),
('Abercrombie & Fitch', 'mid', '{preppy}', 'fashion post. Style: preppy, casual, denim. Brands: Abercrombie & Fitch. Price: mid.', 9),
('Madewell', 'mid', '{coastal,vintage}', 'fashion post. Style: casual denim, coastal, easy classics. Brands: Madewell. Price: mid.', 10),
('J.Crew', 'mid', '{preppy,workwear}', 'fashion post. Style: preppy, workwear, classic. Brands: J.Crew. Price: mid.', 11),
('Everlane', 'mid', '{minimalist}', 'fashion post. Style: minimalist, ethical basics. Brands: Everlane. Price: mid.', 12),
('Free People', 'mid', '{boho,cottagecore,western}', 'fashion post. Style: boho, cottagecore, western. Brands: Free People. Price: mid.', 13),
('Lululemon', 'mid', '{athleisure}', 'fashion post. Style: athleisure, activewear. Brands: Lululemon. Price: mid.', 14),
('Nike', 'mid', '{streetwear,athleisure}', 'fashion post. Style: streetwear, sneakers, athleisure. Brands: Nike. Price: mid.', 15),
('Levi''s', 'mid', '{vintage,western,grunge}', 'fashion post. Style: vintage denim, western, americana. Brands: Levi''s. Price: mid.', 16),
('Urban Outfitters', 'mid', '{y2k,grunge,boho}', 'fashion post. Style: Y2K, grunge, boho, indie. Brands: Urban Outfitters. Price: mid.', 17),
('Reformation', 'premium', '{cottagecore,coastal,glam}', 'fashion post. Style: feminine dresses, coastal, date night. Brands: Reformation. Price: premium.', 18),
('Ganni', 'premium', '{scandi}', 'fashion post. Style: scandi, playful prints, Copenhagen. Brands: Ganni. Price: premium.', 19),
('COS', 'premium', '{minimalist,scandi}', 'fashion post. Style: minimalist, architectural, scandi. Brands: COS. Price: premium.', 20),
('Arc''teryx', 'premium', '{gorpcore}', 'fashion post. Style: gorpcore, technical outdoor. Brands: Arc''teryx. Price: premium.', 21),
('Ralph Lauren', 'premium', '{preppy,old_money}', 'fashion post. Style: preppy, old money, classic American. Brands: Ralph Lauren. Price: premium.', 22),
('Coach', 'premium', '{vintage,workwear}', 'fashion post. Style: leather bags, vintage americana. Brands: Coach. Price: premium.', 23),
('Toteme', 'premium', '{scandi,old_money,minimalist}', 'fashion post. Style: scandi, quiet luxury, minimalist. Brands: Toteme. Price: premium.', 24),
('Gucci', 'luxury', '{glam,vintage}', 'fashion post. Style: glam, maximalist, heritage. Brands: Gucci. Price: luxury.', 25),
('Prada', 'luxury', '{minimalist,workwear}', 'fashion post. Style: intellectual minimalist, luxury. Brands: Prada. Price: luxury.', 26),
('Miu Miu', 'luxury', '{coquette,y2k}', 'fashion post. Style: coquette, girly, playful luxury. Brands: Miu Miu. Price: luxury.', 27),
('The Row', 'luxury', '{old_money,minimalist}', 'fashion post. Style: quiet luxury, minimalist, old money. Brands: The Row. Price: luxury.', 28),
('Loewe', 'luxury', '{scandi,glam}', 'fashion post. Style: artistic luxury, statement bags. Brands: Loewe. Price: luxury.', 29),
('Saint Laurent', 'luxury', '{glam,grunge}', 'fashion post. Style: rock glam, evening, luxury. Brands: Saint Laurent. Price: luxury.', 30);
